# Generated by Django 5.0.2 on 2024-03-02 00:59

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='movie_covers/')),
                ('image', models.ImageField(upload_to='movies/')),
                ('release_date', models.DateField()),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('views_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('TR', 'Top Rated'), ('TN', 'Trending Now'), ('MP', 'Most Popular')], max_length=2)),
                ('category', models.CharField(choices=[('CO', 'Comedy'), ('DR', 'Drama'), ('AC', 'Action'), ('RO', 'Romance'), ('AD', 'Adventure')], max_length=2)),
                ('new_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title', unique=True)),
                ('genres', models.ManyToManyField(to='core.geners')),
            ],
        ),
    ]
