# Generated by Django 5.0.3 on 2024-04-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover', models.ImageField(upload_to='banners/')),
                ('category', models.CharField(choices=[('CO', 'Comedy'), ('DR', 'Drama'), ('AC', 'Action'), ('RO', 'Romance'), ('AD', 'Adventure')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cover_photo',
        ),
    ]
