# Generated by Django 5.0.3 on 2024-04-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banners_remove_movie_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Side_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('picture', models.ImageField(upload_to='Side-Pics/')),
            ],
        ),
    ]
