# Generated by Django 5.0.3 on 2024-04-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_side_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='side_items',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
