# Generated by Django 5.0.4 on 2024-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movie_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='category',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Action', 'Action'), ('Romance', 'Romance'), ('Adventure', 'Adventure')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Action', 'Action'), ('Romance', 'Romance'), ('Adventure', 'Adventure')], max_length=10),
        ),
    ]
